services:
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the test results and reports outside the container
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./e2e:/app/e2e
      - ./playwright.config.ts:/app/playwright.config.ts
      # Use named volume for node_modules to avoid reinstalling
      - playwright-node-modules:/app/node_modules
    environment:
      # Set environment variables for Playwright
      - CI=true
      - NODE_ENV=test
    # Use the command from environment variable or fall back to default
    command: ${PLAYWRIGHT_TEST_COMMAND:-npm run test:e2e}
    ports:
      # Expose the dev server port
      - "5174:5174"
    # Ensure the container has enough resources
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

# Named volumes for persisting data between container runs
volumes:
  playwright-node-modules:
