version: '3'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  sonarscanner:
    build:
      context: .
      dockerfile: Dockerfile.sonarscanner
    container_name: sonarscanner
    depends_on:
      - sonarqube
    volumes:
      - .:/usr/src
      - ./coverage:/usr/src/coverage
    networks:
      - sonarqube-network
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      # Default credentials - change in production
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=admin

networks:
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
