name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          npm install -g docsify-cli
      
      - name: Build with Docsify
        run: |
          mkdir -p build
          # Copy all documentation files including _sidebar.md
          cp -r docs/* build/
          # Verify that _sidebar.md was copied
          if [ -f build/_sidebar.md ]; then
            echo "_sidebar.md copied successfully"
          else
            echo "ERROR: _sidebar.md was not copied correctly!"
            exit 1
          fi
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta charset="UTF-8">
            <title>Poly Micro Manager Documentation</title>
            <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/themes/vue.css">
          </head>
          <body>
            <div id="app"></div>
            <script>
              let svgCounter = 0;
              window.$docsify = {
                name: "Poly Micro Manager",
                repo: "siriknikita/poly-micro-frontend-demo",
                loadSidebar: true,
                subMaxLevel: 3,
                auto2top: true,
                homepage: "README.md",
                markdown: {
                  renderer: {
                    code(code, lang) {
                      if (lang === "mermaid" && window.mermaid) {
                        const svgName = `mermaid-svg-${svgCounter++}`;
                        const MERMAID_CONTAINER_ID = `${svgName}-container`;
                        // Asynchronously render Mermaid diagram
                        window.mermaid.render(svgName, code).then(({ svg }) => {
                          const containerElement = document.querySelector(`#${MERMAID_CONTAINER_ID}`);
                          if (containerElement) {
                            containerElement.innerHTML = svg;
                          } else {
                            console.error(`Error: #${MERMAID_CONTAINER_ID} not found`);
                          }
                        }).catch(err => {
                          console.error("Mermaid rendering error:", err);
                          return `<pre>Error rendering Mermaid diagram: ${err.message}</pre>`;
                        });
                        // Return a placeholder div for the diagram
                        return `<div class="mermaid" id="${MERMAID_CONTAINER_ID}"></div>`;
                      } else if (lang === "mermaid") {
                        // Mermaid not loaded yet, display raw code
                        return `<pre>Mermaid library not loaded. Please refresh the page.</pre>`;
                      }
                      return this.origin.code.apply(this, arguments);
                    },
                  },
                },
              };
            </script>
            <!-- Docsify core script -->
            <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
            <!-- Mermaid library (UMD version) -->
            <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
            <script>
              // Initialize Mermaid after the library is loaded
              window.mermaid.initialize({
                startOnLoad: false, // We control rendering manually
                theme: "default",
                securityLevel: "loose", // Allows HTML labels and interactivity
                flowchart: { useMaxWidth: true, htmlLabels: true },
              });
            </script>
            <!-- PrismJS for syntax highlighting -->
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-typescript.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-jsx.min.js"></script>
          </body>
          </html>' > build/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
