name: PR Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize] # Be explicit about the events

  workflow_dispatch: # Keep manual trigger for debugging

jobs:
  log-trigger:
    name: Log Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Log Pull Request Event
        run: echo "Pull request event triggered for PR \#${{ github.event.pull_request.number }} with action ${{ github.event.action }}"

  check-actor:
    name: Check PR Author
    needs: log-trigger # Ensure this runs after the log
    runs-on: ubuntu-latest
    outputs:
      is_bot: ${{ steps.set.outputs.is_bot }}
    steps:
      - id: set
        run: |
          if [ "${{ github.actor }}" = "github-actions[bot]" ]; then
            echo "is_bot=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_bot=false" >> "$GITHUB_OUTPUT"
          fi

  # Main validation job
  validate:
    name: Validate PR
    needs: check-actor
    runs-on: ubuntu-latest
    if: needs.check-actor.outputs.is_bot != 'true'
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Lint check (errors only)
        run: npm run lint:errors

      - name: Run tests
        run: npm test -- --run

  # Auto-merge PR when checks pass
  auto-merge:
    name: Auto-merge PR
    needs: [validate]
    runs-on: ubuntu-latest
    # Run if the validation job succeeded
    if: |
      always() && 
      needs.validate.result == 'success'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install script dependencies
        run: |
          cd .github/scripts
          npm install
          cd ../..

      - name: Auto-merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          # Execute the auto-merge script directly with Node.js
          node .github/scripts/auto-merge-pr.js