name: PR Checks

on:
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Check for lock file
        id: check-lock
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "has_lock=true" >> $GITHUB_OUTPUT
          else
            echo "has_lock=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies (with lock)
        if: steps.check-lock.outputs.has_lock == 'true'
        run: npm ci
      
      - name: Install dependencies (without lock)
        if: steps.check-lock.outputs.has_lock != 'true'
        run: npm install
      
      - name: Lint check (errors only)
        run: npm run lint:errors
        # This will fail only on errors, not warnings
      
      - name: Run tests
        run: npm test -- --run
        # This will run all tests once and exit, not in watch mode
