name: PR Checks

on:
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-actor:
    name: Check PR Author
    runs-on: ubuntu-latest
    outputs:
      is_bot: ${{ steps.set.outputs.is_bot }}
    steps:
      - id: set
        run: |
          if [ "${{ github.actor }}" = "github-actions[bot]" ]; then
            echo "is_bot=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_bot=false" >> "$GITHUB_OUTPUT"
          fi

  # Main validation job
  validate:
    name: Validate PR
    needs: check-actor
    runs-on: ubuntu-latest
    if: needs.check-actor.outputs.is_bot != 'true'
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Lint check (errors only)
        run: npm run lint:errors

      - name: Run tests
        run: npm test -- --run

  # Job that always succeeds for bot PRs to satisfy required checks
  bot-success:
    name: Auto-approve Bot PR
    needs: check-actor
    runs-on: ubuntu-latest
    if: needs.check-actor.outputs.is_bot == 'true'
    permissions:
      statuses: write
      checks: write
    steps:
      - name: Mark bot PR as validated
        run: echo "Bot PR detected, marking as successful."