name: Update Release Notes

on:
  push:
    tags:
      - 'v*'  # Run workflow when a tag starting with 'v' is pushed (e.g., v1.3.0)

jobs:
  update-release:
    runs-on: ubuntu-latest
    # Add permissions needed for pushing to the repository
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
      checks: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for commit messages
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Generate changes from commit messages
        run: |
          # Get all commits since the last tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag, get all commits
            COMMITS=$(git log --pretty=format:"%s" | grep -v "Merge")
          else
            # Get commits between the previous tag and the current tag
            COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"%s" | grep -v "Merge")
          fi
          
          # Extract changes based on commit types
          echo "[" > changes.json
          
          # Process feature commits
          FEATURES=$(echo "$COMMITS" | grep -i "^feat" || echo "")
          if [ ! -z "$FEATURES" ]; then
            while IFS= read -r line; do
              DESCRIPTION=$(echo "$line" | sed -E 's/^feat(\([^)]+\))?:\s*//')
              echo "  {" >> changes.json
              echo "    \"type\": \"feature\"," >> changes.json
              echo "    \"description\": \"$DESCRIPTION\"" >> changes.json
              echo "  }," >> changes.json
            done <<< "$FEATURES"
          fi
          
          # Process improvement commits
          IMPROVEMENTS=$(echo "$COMMITS" | grep -i "^improve\|^refactor\|^perf" || echo "")
          if [ ! -z "$IMPROVEMENTS" ]; then
            while IFS= read -r line; do
              DESCRIPTION=$(echo "$line" | sed -E 's/^(improve|refactor|perf)(\([^)]+\))?:\s*//')
              echo "  {" >> changes.json
              echo "    \"type\": \"improvement\"," >> changes.json
              echo "    \"description\": \"$DESCRIPTION\"" >> changes.json
              echo "  }," >> changes.json
            done <<< "$IMPROVEMENTS"
          fi
          
          # Process fix commits
          FIXES=$(echo "$COMMITS" | grep -i "^fix" || echo "")
          if [ ! -z "$FIXES" ]; then
            while IFS= read -r line; do
              DESCRIPTION=$(echo "$line" | sed -E 's/^fix(\([^)]+\))?:\s*//')
              echo "  {" >> changes.json
              echo "    \"type\": \"fix\"," >> changes.json
              echo "    \"description\": \"$DESCRIPTION\"" >> changes.json
              echo "  }," >> changes.json
            done <<< "$FIXES"
          fi
          
          # Process breaking change commits
          BREAKING=$(echo "$COMMITS" | grep -i "BREAKING CHANGE" || echo "")
          if [ ! -z "$BREAKING" ]; then
            while IFS= read -r line; do
              DESCRIPTION=$(echo "$line" | sed -E 's/^.*BREAKING CHANGE:\s*//')
              echo "  {" >> changes.json
              echo "    \"type\": \"breaking\"," >> changes.json
              echo "    \"description\": \"$DESCRIPTION\"" >> changes.json
              echo "  }," >> changes.json
            done <<< "$BREAKING"
          fi
          
          # Remove trailing comma if exists
          sed -i '$ s/,$//' changes.json
          
          echo "]" >> changes.json
          
          # Show generated changes
          cat changes.json
      
      - name: Update release file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure VERSION is set from the environment
          # We use the VERSION that was set in the 'Extract version from tag' step
          echo "Using VERSION=$VERSION"
          
          # Create title based on version
          TITLE="Version $VERSION Release"
          
          # Create description
          DESCRIPTION="This release includes new features, improvements, and bug fixes."
          
          # Update the release file
          node scripts/update-release.js --version=$VERSION --title="$TITLE" --description="$DESCRIPTION" --changes=./changes.json
          
          # Create a new branch
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b release-update-v${VERSION}

          git add .
          git commit -m "Feat: Update release notes for v${VERSION}"
          
          # Set remote URL with token for authentication
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git remote set-url origin "$REPO_URL"
          
          # Push the branch to remote
          git push --set-upstream origin release-update-v${VERSION}
      
      - name: Set up GitHub CLI
        run: |
          # GitHub CLI is pre-installed on GitHub-hosted runners
          # Output the version for debugging
          gh --version
          # Make sure the directory exists
          mkdir -p "$GH_CONFIG_DIR"
          
          # Authenticate GitHub CLI using environment variable
          # This is more reliable than using echo
          gh auth setup-git
        env:
          GH_CONFIG_DIR: /home/runner/gh_config
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Note on authentication
        run: echo "Authentication is now handled in the Set up GitHub CLI step"

      - name: Create Pull Request using GitHub CLI
        run: |
          # Ensure GitHub CLI is authenticated
          export GH_CONFIG_DIR=/home/runner/gh_config
          
          PR_TITLE="Feat: Update release notes for v${VERSION}"
          
          # Create PR and capture the output
          PR_OUTPUT=$(gh pr create \
          --base main \
          --head release-update-v${VERSION} \
          --title "$PR_TITLE" \
          --body "This PR updates the release notes for version v${VERSION}.\n\nAutomated PR created by GitHub Actions.")
          
          # Extract PR number and URL from the output
          PR_URL=$PR_OUTPUT
          PR_NUMBER=$(echo $PR_URL | sed -E 's|.*/([0-9]+)$|\1|')
          
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "Created PR #${PR_NUMBER}: $PR_URL"
        id: create_pr
        env:
          GH_CONFIG_DIR: /home/runner/gh_config
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for status checks
        run: |
          echo "Checking status of PR #${PR_NUMBER}"
          
          for i in {1..10}; do
            gh pr checks $PR_NUMBER && break
            sleep 30
          done
        env:
          GH_CONFIG_DIR: /home/runner/gh_config
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Pull Request Auto-Merge
        run: |
          echo "Enabling auto-merge for PR #${PR_NUMBER}"
          
          # Wait for checks to pass before merging
          sleep 60 # Give time for PR checks to start
          
          # Enable auto-merge for the PR
          gh pr merge --auto --merge "$PR_NUMBER"
          
          # Approve the PR
          gh pr review "$PR_NUMBER" --approve
        env:
          GH_CONFIG_DIR: /home/runner/gh_config
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
